### ISSUE TITLE
Add text re. use of constrained voucher with TLS

### ISSUE THREAD

**Issue by toerless** [anima-wg/constrained-voucher#115]
From 05/06/2021 meeting:

Constrained voucher does NOT depend on use of DTLS. The choice of transport (DTLS/TLS between pledge and proxy, or directly to registrar is based on preference of pledge.
- Commonly, pledges using constrained vouchers would likely prefer DTLS as the most common transport code basis
- But there can be exception: Code-basis written for constrained DTLS-only platforms may be shared with other platforms that also use TLS and may prefer TLS because they may use WiFi.

Sugges to add accordingly text to draft to make this clear.

**Comment by EskoDijk** [comment]
Agree, the text could be generalized to also include TLS i.e. CoAP over TLS. To be checked if this impacts a Join Proxy, which in a typical implementation may relay DTLS records one by one to the Registrar address.

Is HTTP over TLS also in scope of this proposal? If so it gets quite close again to BRSKI except for the voucher/voucher-req formats.

**Comment by mcr** [comment]
Do we use shortened paths when doing constrained-voucher over HTTPS?

**Comment by EskoDijk** [comment]
Discussion: some devices have a built-in stack / chip that can do HTTPS (e.g. on WiFi hw). This case should be supported; adding the constrained voucher formats on top of HTTPS. CoAP over TLS isn't intended.

**Comment by csosto-pk** [comment]
> Do we use shortened URI paths when doing constrained-voucher over HTTPS?
> (probably not)

Imo no. Going back to HTTPS this is plain BRSKI. 

I understand that a L7 standard would not care about the transport protocol, but in our case we already have a L7 standard and we are just adjusting it for the COAP world (constrained). 

Supporting constrained voucher URIs in the COAP and HTTP cases is unnecessary complication for implementers imo. Either you are constrained and do COAP/constrained voucher or you are not constrained and you do plain old BRSKI over HTTPS.

**Comment by toerless** [comment]
Btw. i have no strong opinion, i just captured what was discussed in the meeting.
I am curious though to understand the arguments on either side.

I thought a key part of constrained voucher was also the different encoding
options of the voucher, and that would stay even when using HTTPs instead of
DTLS/COAP

Also, the complication would simply be for the text of the document but
not for implementers of constrained nodes. Only a registar would need to
support all the variations of BRSKI/constrained vouchers that it needs to
serve all the pledges it wants to support.

Thats how i imagine the pro arguments.

Cheers
    Toerless

On Thu, May 13, 2021 at 09:40:38AM -0700, Panos K. wrote:
> > Do we use shortened URI paths when doing constrained-voucher over HTTPS?
> > (probably not)
> 
> Imo no. Going back to HTTPS this is plain BRSKI. 
> 
> I understand that a L7 standard would not care about the transport protocol, but in our case we already have a L7 standard and we are just adjusting it for the COAP world (constrained). 
> 
> Supporting constrained voucher URIs in the COAP and HTTP cases is unnecessary complication for implementers imo. Either you are constrained and do COAP/constrained voucher or you are not constrained and you do plain old BRSKI over HTTPS. 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/anima-wg/constrained-voucher/issues/115#issuecomment-840683546

-- 
---
***@***.***

**Comment by EskoDijk** [comment]
So to capture this; we can choose among either option A) or B) , for protocols permitted:

A) There are only 2 flavors a Pledge could use - 
   1] HTTPS BRSKI with CMS/JSON payloads per draft-anima-bootstrapping-keyinfra
   2] CoAPS BRSKI with COSE/CBOR payloads per draft-anima-constrained-voucher

B) 
   1] HTTPS BRSKI with CMS/JSON payloads per draft-anima-bootstrapping-keyinfra
   2] CoAPS BRSKI with COSE/CBOR payloads per draft-anima-constrained-voucher
   3] HTTPS BRSKI per draft-anima-bootstrapping-keyinfra but using COSE/CBOR payloads per draft-anima-constrained-voucher.  This only changes the voucher-request and voucher payloads , w.r.t. draft-anima-bootstrapping-keyinfra. EST remains same so EST-coaps is not used.

So 3] above can be seen as classic BRSKI with a different voucher/voucher-request encoding as Toerless suggested also.
The creation of this issue already suggests option B) is intended.

**Comment by mcr** [comment]
4] HTTPS BRSKI per draft-anima-bootstrapping-keyinfra but using JOSE/JSON payloads per draft-richardson-anima-jose-voucher (as this is something some sectors prefer)

In general, I prefer that Registrar's be flexible in what they accept, and that pledges implement only one thing.
A single firmware load could work well with both 802.15.4 interfaces and wifi interfaces.  
For instance, some wifi interfaces include https/TLS offload.  This is the case for many Arduino level devices.

**Comment by toerless** [comment]
The argument sounds good to me (nonwithstanding any arguments contrary to this that i am unaware of.

It would even be better if this explanation text by michael was included into the text of the draft for readers who might wonder about the persmission of TLS as an option.

Cheers
    Toerless

**Comment by mcr** [comment]
PvdS says not to enumerate all possibilities, because there will be more tomorrow.
