### ISSUE TITLE
Use of CoAP 4.03 Forbidden vs 4.01 Unauthorized

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#122]
BRSKI defines that HTTP 403 is used by MASA or Registrar in case a received Voucher Request is not signed correctly. In CoAP this would be 4.03.   However, also 4.01 Unauthorized exists in CoAP - just to check if we need to consider this? There is no clear 4.01/4.03 difference as far as I can tell.

Another point: if the MASA responds 403, and the Registrar propagates this back to the Pledge with a 4.03, then the Pledge is unable to tell whether its own Voucher Request was badly signed or whether the Registrar's Voucher Request to MASA was badly signed, or both. (The Registrar also cannot tell whether its own VR was badly signed, or the Pledge's VR, or both.)
This may not be a big issue? "Something is wrong" is the message.

One example of "Registrar bad signing" can be a Registrar certificate that is non-cmcRA. MASA will reject that.

**Comment by petervanderstok** [comment]
Actually, when the signature is incorrect, it means that the certificate 
with the public key is incompatible.
It may also mean that RV is not signed at all, or that the signature is 
missing, etc. etc.

I send an ascii error message with the 4.xx error for my own 
understanding of the cause of the problem, but do we want to standardize 
that?

The number of possibilities per 4.xx return code is really large; and I 
am not looking foward to analyse all the possibilities.

cheerio,

Peter

Esko Dijk schreef op 2021-06-25 11:44:

> BRSKI defines that HTTP 403 is used by MASA or Registrar in case a 
> received Voucher Request is not signed correctly. In CoAP this would be 
> 4.03. However, also 4.01 Unauthorized exists in CoAP - just to check if 
> we need to consider this? There is no clear 4.01/4.03 difference as far 
> as I can tell.
> 
> Another point: if the MASA responds 403, and the Registrar propagates 
> this back to the Pledge with a 4.03, then the Pledge is unable to tell 
> whether its own Voucher Request was badly signed or whether the 
> Registrar's Voucher Request to MASA was badly signed, or both. (The 
> Registrar also cannot tell whether its own VR was badly signed, or the 
> Pledge's VR, or both.)
> This may not be a big issue? "Something is wrong" is the message.
> 
> One example of "Registrar bad signing" can be a Registrar certificate 
> that is non-cmcRA. MASA will reject that.
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] https://github.com/anima-wg/constrained-voucher/issues/122
[2]

**Comment by mcr** [comment]
> Another point: if the MASA responds 403, and the Registrar propagates this back to the Pledge with a 4.03, then the Pledge is unable to tell whether its own Voucher Request was badly signed or whether the Registrar's Voucher Request to MASA was badly signed, or both. (The Registrar also cannot tell whether its own VR was badly signed, or the Pledge's VR, or both.)
> This may not be a big issue? "Something is wrong" is the message.

This might be a good place where the 403 gets translated as 401.

**Comment by mcr** [comment]
I think that 403 is appropriate from a MASA when the Registrar is not recognised.
(whether or not the signature is valid may be unknowable, because the MASA might not have a key it can use to validate)

**Comment by EskoDijk** [comment]
Baseline Proposals:
* Don't standardize any diagnostic (error) messages within CoAP error responses, BRSKI also doesn't go this far.
* Standardize the CoAP codes for Registrar to respond to a similar level as done in BRSKI for the Registrar. This may not require anything except saying that the equivalent BRSKI HTTP codes are mapped to CoAP (so e.g. 403 becomes 4.03)
* For MASA, BRSKI already defines the (HTTP) response codes so we don't have to say anything about it.

As to my "another point" I did some investigation and found that BRSKI (Section 5.3) defines that the registrar SHOULD return 404 / 4.04 in case it cannot validate the Voucher Request of the Pledge.  So that means the Pledge can distinguish the case of "Registrar didn't accept it" (4.04) versus "MASA didn't accept me or it didn't accept the Registrar" (4.03) and we don't need 4.01.

By the way the behavior I mention of the Registrar that "propagates" the MASA's success or error code to the Pledge was my assumption based on the title of Section 5.6 "MASA and Registrar Voucher Response" but there is in BRSKI no normative behavior it seems for propagation of error status back to the Pledge.

**Comment by EskoDijk** [comment]
Could use by default the MASA's code and can translate directly to coap -> so coap 4.04
SHOULD do the code translation?

**Comment by EskoDijk** [comment]
I updated the text by moving the new section to the right place (should be under "BRSKI" / 8995 updates) and minor fixes. Note the response codes are in all Sections 5.* , not just 5.6 so I adapted this.
