### ISSUE TITLE
Franke secdir review: improve introduction to make document stand alone better

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#124]
df> Having no prior familiarity with the ANIMA WG or its output, I found the introductory section of this draft rather bewildering. 
df> The document I wanted to read for background, RFC 8366, is cited a few sentences in, but the context didn't make it clear that this was where I wanted to look. 
df> Please provide a paragraph or so worth of background about the ecosystem that this draft lives in before launching into protocol-specific jargon like "voucher" and "pledge".

**Comment by EskoDijk** [comment]
Also the other relevant background drafts are mentioned, bootstrapping-keyinfra (RFC 8995) and coap-est as well. I think one needs to read at least RFC 8995 as required background.

**Comment by mcr** [comment]
> (2) Introduction

    > OSCORE and EDHOC are suddenly used and not introduced.
    > Terms, such as 'Pledge' or 'Registrar' could be better introduced or it should
    > be very clearly stated that this memo cannot be used without a clear
    > understanding of other documents (and which documents that exactly are and
    > why). It is not very clear to the reader why YANG and SID are suddenly
    > appearing here (which again becomes pretty obvious when you read other
    > documents). In general, the Intro requires more context.
