### ISSUE TITLE
Add in Section 6 that Registrar adopts the Voucher Request format used by the Pledge

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#129]
As discussed during interop talks: 
* If the Pledge uses application/voucher-cose+cbor Voucher Request, then Registrar uses the same towards MASA
* If the Pledge uses application/voucher-cms+json Voucher Request, then Registrar uses the same towards MASA

The architecture idea behind this is that Registrar must be most flexible (able to handle any formats, any vendors, any evolution/situations etc) while the Pledge and MASA may be more simple i.e. just support one format.

**Comment by petervanderstok** [comment]
Hi,

pledge is more simple, yes; MASA may go though more updates in his 
lifetime and is probably not simple.

Peter

OLD
while the Pledge and MASA may be more simple i.e. just support one 
format.
NEW
while the Pledge  may be more simple i.e. just supports one format.
Esko Dijk schreef op 2021-07-19 10:13:

> As discussed during interop talks:
> 
> * If the Pledge uses application/voucher-cose+cbor Voucher Request, 
> then Registrar uses the same towards MASA
> * If the Pledge uses application/voucher-cms+json Voucher Request, then 
> Registrar uses the same towards MASA
> 
> The architecture idea behind this is that Registrar must be most 
> flexible (able to handle any formats, any vendors, any 
> evolution/situations etc) while the Pledge and MASA may be more simple 
> i.e. just support one format.
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] https://github.com/anima-wg/constrained-voucher/issues/129
[2]

**Comment by EskoDijk** [comment]
Agreed; the MASA also needs to evolve with e.g. new device types and new voucher formats as needed. 
What I meant is that MASA only needs to support the Voucher Request format that all the Pledges of that same (1) Vendor can potentially send to MASA. While Registrar needs to support all the Voucher Request formats that Pledges of different (N) Vendors can send to it if we introduce the requirement that the Registrar must use "same as the Pledge's" format towards MASA.

**Comment by EskoDijk** [comment]
One open question on this issue is: could the Registrar ever deviate from this rule to "use the same format"?
What if the Registrar and a specific MASA have some business relation in place, where policies are exchanged and mutually aligned, and the Registrar's user agrees with the device-vendor to use format X (e.g. CMS) for its RVRs? (For whatever reason.)

So we could say a Registrar MUST use the same format as the Pledge did unless some (out-of-band) policy / agreement with MASA says otherwise.
