### ISSUE TITLE
Review HB: The title is misleading and needs to be changed

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#132]
> The title implies that this document defines a message or document called
    > 'Constrained Voucher Artifacts' used in 'Bootstrapping Protocols'. The first
    > sentence contradicts this by saying 'This document defines a protocol'. This
    > "IETF'ler Human" also suspects that "Voucher Artifacts" are kind of redundant,
    > but that was okay in RFC8366 so that seems to be okay here.

**Comment by EskoDijk** [comment]
See also #123 for title change
