### ISSUE TITLE
Review HB: Abstract needs to standalone

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#133]
> The abstract requires more (concise!) context and outline of the general
    > problem so that context-specific terms used can be easily understood, e.g.,
    > 'Pledge' or its relationship to 'owner'. Imagine the abstract being the only
    > thing visible in a document indexing and management system and phrase it as
    > such. The "new" CoAP protocol defined seems to be a complement to an HTTPS
    > protocol, which the reader has to guess is defined either by RFC8366 or BRSKI
    > (this is cleared up early in the Intro). Why is it not CoAPS, if its complement
    > is HTTPS? Ultimately, you shall not use references in an abstract and that is
    > the root cause for this need for guessing here, I think.

**Comment by EskoDijk** [comment]
See PR for new text proposal. Note that still some refs are included in the abstract; seeing that it can be handy to indicate which RFCs are updated in the abstract.  (But can always remove if needed)
