### ISSUE TITLE
Review HB:  clarify what proximity is, and why it is important

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#134]
> (3) Overview of Protocol

    > It is not immediately clear what 'proximity' means here (the term is not listed
    > in the Terminology section). A quick recap of roles and interactions would not
    > hurt, I think, but that can also be addressed by adding more contextual text to
    > the Intro. "Most Pledges using these constrained": maybe just remove the
    > "these" - it made me read it as a back-reference to time-based vouchers. The
    > term "pinned" used here could benefit a from a tad bit more expositional text -
    > it is a term relevant to a lot of security aspects in this memo and deserves a
    > proper introduction.

**Comment by EskoDijk** [comment]
Can we reference RFC 8366 for the 'proximity' proof concept?

**Comment by EskoDijk** [comment]
For 'proximity' concept: To add reference, in Section 4.

**Comment by mcr** [comment]
> Can we reference RFC 8366 for the 'proximity' proof concept?

RFC8366 is actually pretty sparse about proximity.

**Comment by EskoDijk** [comment]
RFC 8995 explains proximity somewhat better I think, but you need to assemble all the text parts together that mention "proximity" to get a complete view - so not a single section we can point to.
