### ISSUE TITLE
how to ignore x5bag in pledge->registrar

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#145]
If the raw voucher-request contains an x5bag with the IDevID certificate in it, the Registrar should probably prefer to use the DTLS Client-Certificate instead.
Is it  enough to just ignore the extraneous x5bag?
Are there cases where there might be some certificate chain in the VR that is different than the one from the TLS handshake that needs to be communicated?
Is there an argument to putting such a chain in the VR, which can be transmitted with block transfer rather than the DTLS handshake fragmenter?

**Comment by petervanderstok** [comment]
I hope there is no such argument.
Let's keep pledge-registrar communication simple.

Peter
Michael Richardson schreef op 2021-07-27 04:14:

> If the raw voucher-request contains an x5bag with the IDevID 
> certificate in it, the Registrar should probably prefer to use the DTLS 
> Client-Certificate instead.
> Is it enough to just ignore the extraneous x5bag?
> Are there cases where there might be some certificate chain in the VR 
> that is different than the one from the TLS handshake that needs to be 
> communicated?
> Is there an argument to putting such a chain in the VR, which can be 
> transmitted with block transfer rather than the DTLS handshake 
> fragmenter?
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] https://github.com/anima-wg/constrained-voucher/issues/145
[2]

**Comment by toerless** [comment]
The term raw voucher-request is not in the constrained voucher draft.
Would be good to define it in terminology when you want to use it.
I guess you are talking about a voucher request from the pledge
to the registrar where the pledge has no certificate but just
a public key pair ? But if the pledge doesn't have a key but only
a publik key pair, how then would it be able to use a certificate
in DTLS ?

Cheers
    Toerless

**Comment by EskoDijk** [comment]
See #142 , somewhat duplicate issue about use of x5bag in Pledge's VR

**Comment by EskoDijk** [comment]
Merging this issue with the #142 one, closing current issue for this reason.
