### ISSUE TITLE
RVR -- CMS, what is inside?

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#147]
When MASA receives CMS signed voucher-request.
What is the format of the prior-signed-voucher-request?
Is it CMS? or is it COSE/CBOR, or is it JSON.

Why can't we assume to be the same...
{parboiled-VR-CMS   { raw-VR-CMS? }}

BRSKI-ASYNC has different problem:  when Registrar forwards voucher-request, uses Accept: header to specify format of returned voucher.
(If Accept: not present, then assume same format as request)

**Comment by mcr** [comment]
We need to clarify in text that parboiled is same format as raw, but that it is over HTTPS, not CoAPS.

**Comment by EskoDijk** [comment]
See #129 for partly duplicate issue. 
So when MASA parses the parboiled VR (whether CMS or COSE or ...) , it will assume the raw VR inside has the same format and tries to parse it like that. 

See #129 for further discussion on if/when/why Registrar could deviate from this.

**Comment by mcr** [comment]
fixed by #129

**Comment by EskoDijk** [comment]
Then I think we can close this issue!
