### ISSUE TITLE
interop issue with ecdsa

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#158]
ED rejects ECDSA signature from PvD. 
On a voucher and voucher-request, using COSE signed CBOR.
CoseSign1, using mbedtls ecdsa signature.

**Comment by mcr** [comment]
On this issue, do we have some examples from @petervanderstok and @EskoDijk  that we could include in the document?
Do we already have them, and we just need to figure out where the problem was?

**Comment by EskoDijk** [comment]
Closing issue, see #259 : to verify the new examples.
