### ISSUE TITLE
define a pure CBOR (not signed) voucher request

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#20]
It would be nice and consistent to allow a "pure CBOR" voucher request. This would be identical to the signed CBOR voucher request, except it's not signed so has another CoAP Content-Format. E.g. application/cbor (60).   BRSKI-16 supports non-signed voucher requests with the application/json content type. Perhaps this is already allowed by the current draft however it was not yet immediately clear to me that non-signed CBOR was supported.

This type could also be added to the discovery example, i.e. instead of discovering:
  </est/rv>; rt="ace.est/rv";ct=50 TBD2 16
it would be:
  </est/rv>; rt="ace.est/rv";ct=50 60 TBD2 16
to show that the Registrar supports both JSON and CBOR non-signed voucher requests.

**Comment by petervanderstok** [comment]
Hi Esko,

good remark; will be done.

Peter
Esko Dijk schreef op 2018-08-27 10:13:

> It would be nice and consistent to allow a "pure CBOR" voucher request. This would be identical to the signed CBOR voucher request, except it's not signed so has another CoAP Content-Format. E.g. application/cbor (60). BRSKI-16 supports non-signed voucher requests with the application/json content type. Perhaps this is already allowed by the current draft however it was not yet immediately clear to me that non-signed CBOR was supported. 
> 
> This type could also be added to the discovery example, i.e. instead of discovering:
> </est/rv>; rt="ace.est/rv";ct=50 TBD2 16
> it would be:
> </est/rv>; rt="ace.est/rv";ct=50 60 TBD2 16
> to show that the Registrar supports both JSON and CBOR non-signed voucher requests. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/anima-wg/constrained-voucher/issues/20
[2]

**Comment by mcr** [comment]
Done in -01.
