### ISSUE TITLE
GET used instead of POST on the /rv resource

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#21]
see A.3: 
  GET coaps://[2001:db8::2:1]:61616]/est/rv
should be
  POST coaps://[2001:db8::2:1]:61616]/est/rv

along with a submitted payload (voucher request). The 2.05 response then should be 2.04 for POST.

**Comment by petervanderstok** [comment]
Thanks, will change.
Esko Dijk schreef op 2018-08-27 10:17:

> see A.3:
> GET coaps://[2001:db8::2:1]:61616]/est/rv
> should be
> POST coaps://[2001:db8::2:1]:61616]/est/rv 
> 
> along with a submitted payload (voucher request). The 2.05 response then should be 2.04 for POST. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/anima-wg/constrained-voucher/issues/21
[2]

**Comment by mcr** [comment]
Done in -01.
