### ISSUE TITLE
interop concerns: proximity assertion encoded as string

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#212]
- need to record what the enumerated values are
- confirm interoperability using integers rather than strings

**Comment by mcr** [comment]
- need to look at what we copy/validate out of the certificates: AuthorityKeyIdentifier.
-

**Comment by mcr** [comment]
- present summary of summary of hackathons to IETF113.
-

**Comment by EskoDijk** [comment]
On "need to record enumerated values"
* Section 9.1.4 and 9.2.4 currently contain examples of the "assertion" field enumeration values.
* Maybe we can just add a complete list of the enumeration values and explanation of how these values can be derived e.g. as Section 9.1.5 or as 9.4.

**Comment by EskoDijk** [comment]
The textual part of this issue (draft update) was done in PR #218 . Marking this issue now with "Interop" label to verify these numbers during the next interop.

**Comment by EskoDijk** [comment]
The current scope of out interop activities is not that big that we can test all of the values. For example, OT-Registrar only tests value 2 "proximity" assertion. So it does not seem to make sense to keep this issue open for interop purposes; closing.
