### ISSUE TITLE
move names from 'Acknowledgements' section into 'Contributors' section

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#219]
Reason: 'Contributors' section is machine-parseable and used for keeping IETF contributors statistics.

**Comment by EskoDijk** [comment]
Possibly relevant (but older) information: https://datatracker.ietf.org/doc/html/draft-carpenter-whats-an-author

**Comment by mcr** [comment]
I prefer Contributors because it's part of the XML, and becomes machine readable.

**Comment by EskoDijk** [comment]
Based on discussion in the Tuesday call, I wanted to use a "contributors" tag in the "Acknowledgements" section to get a nicer looking output than just a bare list of names.

It turned out the "contact" tag is used for this see https://authors.ietf.org/rfcxml-vocabulary#contact 

Due to layout issues/bugs in Kramdown, I needed to use XML tags inside the Markdown.
