### ISSUE TITLE
assertion enum should be mapped to a number in CBOR?

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#22]
currently the "assertion" field is a string, while RFC 8366 defines it as an enumeration with either "proximity", "logged" or "verified". For compactness it is better to define this value as an enum; so should the enum values be defined in this draft?
(or better, some a priori order could be specified like alphabetical or following the order of the formal YANG definition of the enum)

**Comment by petervanderstok** [comment]
Hi Esko,

The constrained-voucher-request and  constrained voucher are augments of
voucher-request and voucher respectively. Consequently assertion is an
enumeration. In the old version an old specification of voucher was
used.
Sorry for the confusion.

Peter
Esko Dijk schreef op 2018-08-27 10:29:

> currently the "assertion" field is a string, while RFC 8366 defines it as an enumeration with either "proximity", "logged" or "verified". For compactness it is better to define this value as an enum; so should the enum values be defined in this draft?
> (or better, some a priori order could be specified like alphabetical or following the order of the formal YANG definition of the enum) 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/anima-wg/constrained-voucher/issues/22
[2]

**Comment by mcr** [comment]
Done in -01.
