### ISSUE TITLE
created-on shown as mandatory in voucher-request tree diagram

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#23]
created-on shown as mandatory in voucher-request tree diagram, while BRSKI-16 defines it as optional.

**Comment by petervanderstok** [comment]
version problem
Esko Dijk schreef op 2018-08-27 11:25:

> created-on shown as mandatory in voucher-request tree diagram, while BRSKI-16 defines it as optional. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/anima-wg/constrained-voucher/issues/23
[2]

**Comment by EskoDijk** [comment]
BRSKI-16 has a change in the created-on field, to make it optional in the voucher-request.
The YANG model Section 3.3 seems to achieve this by:

refine "voucher/created-on" {
        mandatory false;
      }

which makes it optional in the voucher request. And that makes sense, to support Pledges without real-time clock.

**Comment by EskoDijk** [comment]
In any case, if RFC 8366 defines something as mandatory for a *voucher* there's no reason why that thing should be also mandatory in a *voucher request*. They are different things.  (It just happens BRSKI-16 did some inheritance from the RFC 8366 YANG model. And then its fine to disable some fields in the original RFC 8366 format if these are not needed.)

**Comment by petervanderstok** [comment]
"refine" is used to make attribute optional
