### ISSUE TITLE
Specify DTLS 1.3, but tolerate DTLS1.2

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#235]

**Comment by EskoDijk** [comment]
Tasks to be done:

* PROPOSED: Insert a new Section 6.1 that captures all TLS/DTLS related subtopics in one; integrating current 6.1, 6.2, 6.7 and adding an initial subsection on DTLS 1.2 / 1.3 version usage. This will make the overall Section 6 more organized by topic.
* Replace dtls 1.3 draft reference with https://datatracker.ietf.org/doc/html/rfc9147
* Add a reference to DTLS 1.2 RFC 6347
* Say we update the RFC 9148 (EST-coaps) defined DTLS version (either 1.2 or 1.3) to 1.3 RECOMMENDED. (And tolerate 1.2, as was intended? Can we tolerate an obsoleted spec?)

@mcr Any feedback is welcome! I can start on the open issues post-IETF-115.
