### ISSUE TITLE
go through all examples and verify they are still good

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#237]
Based upon interop results, we need to think about if our examples are complete.

**Comment by EskoDijk** [comment]
See issue #215 for a specific element of examples to verify - hereby included in this work item.

**Comment by EskoDijk** [comment]
Working on edits now to update all examples in the draft based on latest interop code.
Where needed (in more complex changes) I create some sub-issues to track. First one created is #244
