### ISSUE TITLE
pinned-domain-cert shown as mandatory in tree diagram of voucher-request

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#24]
pinned-domain-cert shown as mandatory in tree diagram of voucher-request; while in BRSKI-16 it it optional. The Registrar does include it in its request but a Pledge doesn't.

**Comment by petervanderstok** [comment]
version problem
Esko Dijk schreef op 2018-08-27 11:31:

> pinned-domain-cert shown as mandatory in tree diagram of voucher-request; while in BRSKI-16 it it optional. The Registrar does include it in its request but a Pledge doesn't. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/anima-wg/constrained-voucher/issues/24
[2]

**Comment by mcr** [comment]
We want it optional in all. In particular, it may be replaced by proximity-registrar-subject-public-key-info.
So, we need to enhance this in the YANG to make it optional.
