### ISSUE TITLE
pinned-domain-public-key-info -> pinned-domain-subject-public-key-info

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#25]
rename pinned-domain-public-key-info -> pinned-domain-subject-public-key-info

**Comment by petervanderstok** [comment]
Hi ESko,

an old version of ietf-voucher was enhanced.

Peter
Esko Dijk schreef op 2018-08-27 14:24:

> rename pinned-domain-public-key-info -> pinned-domain-subject-public-key-info 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/anima-wg/constrained-voucher/issues/25
[2]

**Comment by mcr** [comment]
Found remaining instances, and renamed.
