### ISSUE TITLE
Is application/voucher-cose+cbor a correct name?

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#264]
Alternative would be: application/voucher-cbor+cose

to signal that it is a Voucher in CBOR format, with a wrapping of COSE around it ("+cose").
Or should it be application/voucher-cose+cbor ?

**Comment by thomas-fossati** [comment]
If you wanted to do `application/voucher-cbor+cose` you'd need to define and register `+cose` in the [SSS registry](https://www.iana.org/assignments/media-type-structured-suffix/media-type-structured-suffix.xhtml) because it's not there yet.

**Comment by EskoDijk** [comment]
Thanks @thomas-fossati, I see now the RFC 6838 guidance on this. The suffix behind the '+' ought to be an already-registered encoding standard. And here the '+cbor' makes sense, as the underlying syntax of the (outer) COSE object is itself also plain CBOR -- besides being COSE. 

Adding `+cose` to the SSS registry would give some complications maybe; for some reason the COSE RFC did not register this.

**Comment by EskoDijk** [comment]
The `+cose` suffix has been requested now, see email thread:
https://mailarchive.ietf.org/arch/msg/cose/Qb9W7ouloS__x7WyiN_AUsH4kXc/

**Comment by EskoDijk** [comment]
If this registration proceeds, then we may change our media type to either one of 
`application/voucher+cose`
`application/voucher-cbor+cose`

**Comment by EskoDijk** [comment]
No input received from media-types WG, next step in process is to send the request to IANA per email. (Checking with mcr who will send the email and if not already sent.)

**Comment by EskoDijk** [comment]
@thomas-fossati FYI I've now linked a PR to request the registration: https://github.com/anima-wg/constrained-voucher/pull/277
