### ISSUE TITLE
Examples voucher/voucher-request to be updated to be consistent with spec text

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#30]
Examples seem out of date; either should be updated to be consistent with latest spec text, or should be marked with a "TBD" and indicating the formats are incorrect and will be updated in a future version of the text.

Specifically out of date in the examples:
 - SID numbers (not defined in main spec text)
 - the "assertion" field value - should be according to enum, with value 0, 1 or 2.  (Not a string value)

**Comment by EskoDijk** [comment]
duplicate of #28 , closing!

**Comment by petervanderstok** [comment]
has been done in version 2 to be published.

Esko Dijk schreef op 2018-09-05 13:33:

> Examples seem out of date; either should be updated to be consistent with latest spec text, or should be marked with a "TBD" and indicating the formats are incorrect and will be updated in a future version of the text. 
> 
> Specifically out of date in the examples: 
> 
> * SID numbers (not defined in main spec text)
> * the "assertion" field value - should be according to enum, with value 0, 1 or 2. (Not a string value)
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/anima-wg/constrained-voucher/issues/30
[2]
