### ISSUE TITLE
Example A.3: POST /est/rv should have a request payload e.g. type 60

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#31]
Example A.3: POST /est/rv should carry a voucher request payload e.g. encoded in plain CBOR (type 60)
Also, the response shows 2.05 -> should be 2.04

**Comment by petervanderstok** [comment]
Hi Esko

Ok for 2.04

Section 5.4 of keyinfra from registrar to MASA, the payload is CMS
enveloped.
So, I will add text to tell that the request is Registrar to MASA.

Cheerio,

Peter

Esko Dijk schreef op 2018-09-05 13:46:

> Example A.3: POST /est/rv should carry a voucher request payload e.g. encoded in plain CBOR (type 60)
> Also, the response shows 2.05 -> should be 2.04 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/anima-wg/constrained-voucher/issues/31
[2]

**Comment by EskoDijk** [comment]
Ok, in that case the POST request should have a signed payload also. Still it would be good to add an example where a Pledge creates a non-signed voucher request.

**Comment by mcr** [comment]
Esko Dijk <notifications@github.com> wrote:
    > Ok, in that case the POST request should have a signed payload also.
    > Still it would be good to add an example where a Pledge creates a
    > non-signed voucher request.

I agree.
I didn't implement the non-signed code path yet, which is why I haven't put
such an example in yet.

**Comment by petervanderstok** [comment]
split into two examples signed and unsigned
