### ISSUE TITLE
Example 6.2.4 contains both pinned-domain-cert and pinned-domain-subject-public-key-info

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#36]
Example 6.2.4 contains both pinned-domain-cert and pinned-domain-subject-public-key-info:
It should be one or the other: either a full cert is pinned, or the raw public key.

(Which one gets selected by the Registrar/MASA? My logic would be that if the Pledge puts in a proximity-registrar-subject-public-key-info in its voucher request, then the Registrar would respond with pinned-domain-subject-public-key-info to facilitate the constrained Pledge. If the Pledge uses proximit-registrar-cert in its request, then the Registrar infers the Pledge is not that constrained and can return pinned-domain-cert.)

**Comment by petervanderstok** [comment]
Hi Esko,

thanks. Good remarks; I started working slowly on the draft

Peter
Esko Dijk schreef op 2019-02-04 05:47:

> Example 6.2.4 contains both pinned-domain-cert and pinned-domain-subject-public-key-info:
> It should be one or the other: either a full cert is pinned, or the raw public key. 
> 
> (Which one gets selected by the Registrar/MASA? My logic would be that if the Pledge puts in a proximity-registrar-subject-public-key-info in its voucher request, then the Registrar would respond with pinned-domain-subject-public-key-info to facilitate the constrained Pledge. If the Pledge uses proximit-registrar-cert in its request, then the Registrar infers the Pledge is not that constrained and can return pinned-domain-cert.) 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/anima-wg/constrained-voucher/issues/36
[2]

**Comment by EskoDijk** [comment]
Updated example in above commit and also partly in commit https://github.com/anima-wg/constrained-voucher/commit/100b2c6fdcbaa0b9a8f9728343d8369753d9c463 . 

Fields that are illegal in Voucher or not advised to be in there are removed.
