### ISSUE TITLE
Example 6.1.4 Voucher Request contains "pinned-domain-cert"

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#37]
Example 6.1.4 Voucher Request contains "pinned-domain-cert"; while one would expect that only in a voucher (response) potentially. See also #36 for Registrar's logic in selecting between full cert or RPK-only. 

It would be good to align examples 6.1.4 and 6.2.4 such that the request example 6.1.4 leads to the voucher example 6.2.4.

**Comment by petervanderstok** [comment]
Hi esko,

thanks,

peter
Esko Dijk schreef op 2019-02-04 05:50:

> Example 6.1.4 Voucher Request contains "pinned-domain-cert"; while one would expect that only in a voucher (response) potentially. See also #36 [1] for Registrar's logic in selecting between full cert or RPK-only. 
> 
> It would be good to align examples 6.1.4 and 6.2.4 such that the request example 6.1.4 leads to the voucher example 6.2.4. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/anima-wg/constrained-voucher/issues/36
[2] https://github.com/anima-wg/constrained-voucher/issues/37
[3]

**Comment by mcr** [comment]
It has become clear that the voucher-request and voucher examples were swapped.
But, pinned-domain-cert does not belong in the voucher-request.
In -03 this is fixed, but better examples from real working implementations will be included, including the full CBOR encoding.

**Comment by EskoDijk** [comment]
Updated example in commit https://github.com/anima-wg/constrained-voucher/commit/100b2c6fdcbaa0b9a8f9728343d8369753d9c463  (commit message forgets to mention this issue...)

Fields that are illegal in Voucher Request or not advised to be in there are removed. Example is specific to Pledge-to-Registrar voucher request now.
