### ISSUE TITLE
"pinned-domain-cert" only a Registrar cert, while RFC 8366 allows pinning others also

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#38]
"pinned-domain-cert" is described in Section 4 as being the Registrar cert. However, RFC 8366 allows more certificates in here, for example to pin the Domain CA cert.  For constrained devices that are still able to perform PKIX/X.509 operations, pinning a single Domain CA cert (instead of the Registrar cert) can work also. 
The draft should provide the rationale to restrict this field to Registrar cert only, because the restriction means it is not a direct translation of RFC 8366 but applies additional restrictions. Then it is good to explain these and why necessary.
Or alternatively, relax the use of the field to comply with RFC 8366 definitions.

One benefit of pinning a Domain CA is that a Registrar cert can at some point change or be revoked, and the pinned trust root will still be valid.

**Comment by EskoDijk** [comment]
@petervanderstok @mcr : any thoughts on this? Note that the Fairhair specs also define the Domain CA as the trust root that is distributed to bootstrapping Pledges. 
Of course the Registrar can be a CA itself (subordinate of the Domain CA) and in that case it can distribute its own certificate as the trust root (pinned-domain-cert) for bootstrapping Pledges.

Ideally the Registrar should decide which CA cert becomes the pinned cert; so the IETF specification should not constrain this.

**Comment by mcr** [comment]
@EskoDijk , I'm not sure what the Fairhair specs are, because I never saw such a thing.
I have been trying to answer this issue weekly since April, and I appologize for being so lame; it's just that it's not a trivial question.
pinning the Registrar Cert is probably just wrong.  The reason to do this is it simplies the pledge's work. Instead of doing PKI operations it can do a memcmp.  The pledge will better anchors via /cacerts request.  
I think this warrants more discussion of pro/con of the different things, and that maybe some applicability should apply, but also the manufacturer would know which their pledge can do.

**Comment by EskoDijk** [comment]
@mcr Ok no problem, I just didn't know if this issue had been seen. The Fairhair spec is at https://www.fairhair-alliance.org/specification/ . It defines "security zones" in a system - a zone is a secured domain with a unique Domain CA as the trust root. This CA issues & signs the operational certificates per regular non-constrained BRSKI/EST requirements. It does allow the Registrar to be the Domain CA itself. If not one and the same, the Registrar certificate set sent during the (D)TLS handshake needs to chain correctly to the Domain CA.

So my view would be: in the constrained-voucher I-D, we define the pinned-domain-cert as the Domain CA cert that will directly issue the operational cert for the Pledge. This complies fully with BRSKI/EST/Fairhair specs.  

If we want to avoid PKI operations during the bootstrap, for more constrained environments, one could additionally require in a derived specification that Domain CA MUST equal the Registrar cert. (And where the Registrar cert MUST have the 'CA: True' in X509v3 Basic Constraints.) I see this as something that the constrained-voucher draft does not have to specify. Rather, constrained-voucher should enable all or most of the BRSKI+EST solution but then implemented using CBOR vouchers. This would include being flexible what to pick as the Domain CA trust anchor. Further specs, like 6tisch zerotouch, or Thread 1.2, that make use of constrained-voucher can of course opt to apply further limitations / specific design choices in order to minimize overhead on the Pledges. For Thread 1.2 for example the Domain CA can be the Registrar itself but need not be; it uses PKI operations to verify cert chains.

I do agree that when RPK is used instead of certs, the flexibility is necessarily limited - in that case the RPK of the Registrar needs to be pinned in the Voucher. But then it has good reasons why the limitation needs to be applied.

**Comment by mcr** [comment]
The Registar can be pinned, or the CA above it, (or above that), as long as it pins something that allows the pledge to evaluate.

**Comment by EskoDijk** [comment]
Updating the text now in the master branch to generalize (not only Registrars can be pinned).

One part of the YANG module text is too restrictive:
"In particular, it assumes that nonce-ful operation is
    always required, that expiration dates are rather weak, as no
    clocks can be assumed, and that the Registrar is identified
    by a pinned Raw Public Key.
"

This is incorrect; the Registrar may be pinned also by its certificate if those are used. I wasn't sure where or how (versioning?) this YANG text is to be changed so this is left open.

**Comment by EskoDijk** [comment]
Update: to check if we "modify" the RFC 8366 YANG description; and whether that needs a (formal) update procedure for that YANG or not.
