### ISSUE TITLE
Inconsistencies in draft for voucher-04 (GitHub) in use of SID values.

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#40]
The situation with SID values is confusing for a long time already, why not release one version with at least a consistent set of values specified in examples, tables and text? 

Voucher request
* Section 6.1.2 states base SID value is 1001150
* Section 6.1.2 "created-on" is 1001156 (note: offset +6 w.r.t. base)
* Example section 6.1.4 uses base SID value 1001050 (but not 1001150 ??)
* Example section 6.1.4 uses "created-on" = 1001056  (note differs from 1001156 in 6.1.2!)

Voucher
* Section 6.2.2 states base SID value is 1001101   (why not 1001100 as in Section 9.4 ?)
* Section 6.2.2 "created-on" is 1001106   (note: offset +5 w.r.t. base value, not +6)
* Example section 6.2.4. uses "created on" 1001107  (not 1001106 as in 6.2.2)

Both Voucher request and Voucher
* Section 1 states "the table of SID values presented here should be considered normative" while Section 6.1.2 contradicts this with "WARNING, obsolete definitions" while it is a SID values table.
* It should also be noted in which range the SID values are reserved - Section 9.4 mentions the range entry-points but it should explain whether these will later on change to lower numbers e.g. in the "expert review range" (draft-ietf-core-sid-06).  Current values/ranges are allocated outside of the draft-ietf-core-sid-06 IANA range altogether. So it feels like a temporary set of values.

**Comment by petervanderstok** [comment]
Hi Esko, 
thanks.

The SID values are now aligned by changing the examples and regenerating
the text.
Remark about obsolete definition is removed.
Section 9.4 mentions that SID values are moved to YANG modules in RFC
range.

One extra remark;
We live with temporary tools that can change versions and are not 
maintained by IETF tools team.
We get no reaction from them when asking support.
One consequence is that lines of SID value table overflow.

Peter
Esko Dijk schreef op 2019-06-11 13:23:

> The situation with SID values is confusing for a long time already, why not release one version with at least a consistent set of values specified in examples, tables and text? 
> 
> Voucher request 
> 
> * Section 6.1.2 states base SID value is 1001150
> * Section 6.1.2 "created-on" is 1001156 (note: offset +6 w.r.t. base)
> * Example section 6.1.4 uses base SID value 1001050 (but not 1001150 ??)
> * Example section 6.1.4 uses "created-on" = 1001056 (note differs from 1001156 in 6.1.2!)
> 
> Voucher 
> 
> * Section 6.2.2 states base SID value is 1001101 (why not 1001100 as in Section 9.4 ?)
> * Section 6.2.2 "created-on" is 1001106 (note: offset +5 w.r.t. base value, not +6)
> * Example section 6.2.4. uses "created on" 1001107 (not 1001106 as in 6.2.2)
> 
> Both Voucher request and Voucher 
> 
> * Section 1 states "the table of SID values presented here should be considered normative" while Section 6.1.2 contradicts this with "WARNING, obsolete definitions" while it is a SID values table.
> * It should also be noted in which range the SID values are reserved - Section 9.4 mentions the range entry-points but it should explain whether these will later on change to lower numbers e.g. in the "expert review range" (draft-ietf-core-sid-06). Current values/ranges are allocated outside of the draft-ietf-core-sid-06 IANA range altogether. So it feels like a temporary set of values.
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/anima-wg/constrained-voucher/issues/40?email_source=notifications&amp;email_token=ADCZGQOL5EHE4PNAGH2PCETPZ6DLNA5CNFSM4HW5IRMKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GYZEKTA
[2]

**Comment by EskoDijk** [comment]
Thanks a lot Peter for the quick update!

A couple of remarks still, on the numbers used in the new version .txt on Github:

6.1.4: example Voucher Request
- for "assertion", the key is correct but the value should be "2" (proximity) instead of "0" (verified) - because the request is asserting proximity to the Registrar identified by the field "proximity-registrar-cert" in the Voucher.
- serial-number SID should be +13 (1001167) , using the 6.1.2 SID values.
- proximity-registrar-cert SID should be +10 (1001164) ; there's also the comment SID=1001069 to be updated to 1001164
- "pinned-domain-subject-public-key-info" field should be "proximity-registrar-subject-public-key-info" with +12 (SID 1001166). 
- 

6.2.4: example Voucher
- serial-number SID should be +11 (SID 1001115), using the 6.2.2 SID values
- the +11 (SID 1001115) item "proximity-registrar-subject-public-key-info" is not defined in the SID table for a Voucher, so should be removed from the example. BRSKI only uses proximity-registrar-cert in Voucher Requests, not in Vouchers.
- the item +8 "pinned-domain-cert" mentions SID = 1001111 , which should be 1001112.

**Comment by petervanderstok** [comment]
Thanks for the pointing out the inconsistencies.

example sids are now aligned with table sids.
Overflow in sid table is removed.
proximity-registrar-subject-public-key-info is replaced with
pinned-domain-subject-public-key-info in voucher

cheerio,

peter

Esko Dijk schreef op 2019-06-13 22:19:

> Thanks a lot Peter for the quick update! 
> 
> A couple of remarks still, on the numbers used in the new version .txt on Github: 
> 
> 6.1.4: example Voucher Request 
> 
> * for "assertion", the key is correct but the value should be "2" (proximity) instead of "0" (verified) - because the request is asserting proximity to the Registrar identified by the field "proximity-registrar-cert" in the Voucher.
> * serial-number SID should be +13 (1001167) , using the 6.1.2 SID values.
> * proximity-registrar-cert SID should be +10 (1001164) ; there's also the comment SID=1001069 to be updated to 1001164
> * "pinned-domain-subject-public-key-info" field should be "proximity-registrar-subject-public-key-info" with +12 (SID 1001166).
> * 
> 
> 6.2.4: example Voucher 
> 
> * serial-number SID should be +11 (SID 1001115), using the 6.2.2 SID values
> * the +11 (SID 1001115) item "proximity-registrar-subject-public-key-info" is not defined in the SID table for a Voucher, so should be removed from the example. BRSKI only uses proximity-registrar-cert in Voucher Requests, not in Vouchers.
> * the item +8 "pinned-domain-cert" mentions SID = 1001111 , which should be 1001112.
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/anima-wg/constrained-voucher/issues/40?email_source=notifications&amp;email_token=ADCZGQKGQFIZV3WZZBDW2A3P2KTWVA5CNFSM4HW5IRMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXU5IVQ#issuecomment-501863510
[2]
