### ISSUE TITLE
Improve text explaining use and need for new content type (due to early allocation)

### ISSUE THREAD

**Issue by toerless** [anima-wg/constrained-voucher#45]
>    A different eContentType of TBD1 is used to indicate that the
>    contents are in a different format than in [RFC8366].

WOuld like to see an improvement of this sentence to something like:

> The eContentType ([RFCxxx]) of TBD1 (id-ct-animaCBORVoucher, see section
> [IANA]) is used to indicate that the contents is a constrained voucher.
> This value is different from the one of a regular voucher in [RFC8366]
> because constrained vouchers can not be handled by parssing code that
> only supports regular vouchers.

- I could not find the word 'eContentType' in rfc7101 which is the
  reference used in the IANA registry, so please use a known word, or
  provide a reference for this word (sorry, this is also missing from
  RFC8366, but there i was co-author and not anal reviewer ;-)

- When someone wants to find this text section from the IANA section to
  see that the use of the registry value is well defined, one wold look
  for TBD1 (in RFC some number). That is not as good as also including
  into this text the name identifier (id-ct-animaCBORVoucher).

- The last part of the paragraph is my best guess at the explanation
  as to why a separate identifier is required (mess up existing RFC833
  parse if we did use the same value). If thats not the correct
  explanation to justify the new value, please write a fitting one.

**Comment by mcr** [comment]
related to #46, no longer needed.
