### ISSUE TITLE
New code point pre-allocated, now to be returned to IANA

### ISSUE THREAD

**Issue by toerless** [anima-wg/constrained-voucher#46]
Date: Wed, 15 Jan 2020 00:28:31 +0000
From: Sabrina Tanamal via RT <iana-prot-param@iana.org>
To: tte@cs.fau.de
Subject: [IANA #1160164] Request for Assignment (smi-numbers)

Dear Toerless,

We've added the following entry to the SMI Security for S/MIME CMS
Content Type (1.2.840.113549.1.9.16.1) registry:

46      id-ct-animaCBORVoucher  [draft-ietf-anima-constrained-voucher]

Please see
https://www.iana.org/assignments/smi-numbers

Best regards,
Sabrina Tanamal
Senior IANA Services Specialist

**Comment by mcr** [comment]
Having removed CMS-signed content, we should return this to IANA.

**Comment by mcr** [comment]
close in email https://mailarchive.ietf.org/arch/msg/anima/eUowiyvwgcocINMIV4K5NJGn9V4/

**Comment by EskoDijk** [comment]
IANA confirmation that it was closed: https://mailarchive.ietf.org/arch/msg/anima/e--md_eP9VdN-iw1YJbmGuhzJyk/
