### ISSUE TITLE
Unclear how MASA obtains Domain CA cert for pinning, in case of COSE-signed Voucher Request

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#49]
In BRSKI (5.5.2  MASA pinning of registrar) it is clear how the MASA can get the complete cert chain of the Registrar from the CMS signature structure. The Registrar's Domain CA cert is included in there and is used as the pinned domain cert in the Voucher.  However, when we now use COSE-signed Voucher Request by the Registrar, the Registrar's Domain CA cert is not included in the COSE-sign structure so the MASA cannot "extract" it per BRSKI 5.5.2.    

It would be good to make more explicit how the MASA should extract the Registrar's Domain CA cert in this case (Note: the Domain CA could be the Registrar itself but not necessarily.)  The obvious candidate is to get it from the DTLS or TLS handshake that Registrar performs with MASA. This is already hinted at in the text in section 6.1.3 / 6.2.3 inside the YANG module description "... it is wasteful ... " but that is not quite clear. When Registrar is using COSE signing the MASA *has* to get the certificate from the handshake if the MASA wants to pin the entire certificate in the Voucher, there seems to be no other option. Section 6.3.2 now mentions "out of band" distribution but that's not very clever if you want automated bootstrapping - it needs to go all in-protocol / in-band.
It should be noted also that this modifies the BRSKI requirement section 5.5.2 on how the pinned Domain CA cert is obtained.

**Comment by mcr** [comment]
Hi, I want to take this conversation to the list.

**Comment by mcr** [comment]
Need to write correct text, maybe put it into masa-considerations, but get the text right, and then figure out what document to put it into.

**Comment by EskoDijk** [comment]
Note that #59 proposes another solution; not obtain the cert chain from the DTLS handshake but from COSE-X509 signing structure x5bag.  This seems a better solution as it is more close to how BRSKI currently works - get the chain from the (CMS) signing structure. If we all agree on this, I would close the current issue and delegate all work to #59.
