### ISSUE TITLE
Update well-known paths to final outcomes of discussion .well-known/est versus .well-known/brski

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#51]
See ANIMA WG discussion of ~ 2020-09-16
Archived-At: <https://mailarchive.ietf.org/arch/msg/anima/UWCTFKTEvubL61p_UGrdFVUV_rc>

**Comment by mcr** [comment]
Given that constrained-BRSKI always takes a pass through /.well-known/core?rt=est, I guess this is not really about the paths themselves, but whether or not one has to ask for rt=brski, rather than rt=est?  How does one ask for both?

**Comment by EskoDijk** [comment]
I created the related issue https://github.com/anima-wg/constrained-voucher/issues/53  which is about being able to skip the discovery phase and just use the well-known paths.

For a client that wants/needs to do discovery, it could ask 2 times using 2 requests:
GET /.well-known/core?rt=ace.est
GET /.well-known/core?rt=ace.brski

It is possible also to do a single wildcard request:
GET /.well-known/core?rt=ace.*

This would return however all of the resources ace.est, ace.brski, ace.est.rv, ace.est.vs, ace.est.es, ace.est.ra so it could be a lengthy response.

Notice I replaced in above sentence the '/' in the section 5 Link Format example resource types to a '.' character ; see https://github.com/anima-wg/constrained-voucher/issues/54 for this.

**Comment by mcr** [comment]
> GET /.well-known/core?rt=ace.brski

Would this be "ace."? or just "brski"?  Is the ace.* important?

**Comment by petervanderstok** [comment]
missing any general rules, you can pretend to be alone in the ietf, (or
oscf, thread,..) and use brski

Peter
Michael Richardson schreef op 2020-10-22 13:44:

>> GET /.well-known/core?rt=ace.brski
> 
> Would this be "ace."? or just "brski"? Is the ace.* important? 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/anima-wg/constrained-voucher/issues/51#issuecomment-714436488
[2]

**Comment by mcr** [comment]
updated URLs.

**Comment by EskoDijk** [comment]
Verified the updated text (and removed some spaces in the link format example also: commit https://github.com/anima-wg/constrained-voucher/commit/7f2c13c27d82c77814c7a17e45a7d02d390f70aa)
Closing this issue since the requested task was done.
