### ISSUE TITLE
Enable .well-known resources, just like those offered by (non-constrained) BRSKI - and skip discovery

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#53]
Current constrained-voucher-08 draft seems to mandate discovery of EST/BRSKI resources, and does not offer well-known paths to these (in the /.well-known/ URI namespace) like BRSKI does.

This is a proposal to add support for all the BRSKI well-known resources. In a constrained network / node , it is a significant saving of resources and reduction of complexity of *not* having to do a discovery step and subsequent parsing of a Link Format file for which the client may not even have parser code available.

Why would a constrained version of a protocol add more message round-trips and overhead for no apparent reason?  Discovery can still be optional for the client of course.

**Comment by EskoDijk** [comment]
Update:
* the draft should define the use of /.well-known/brski/...  resources as per BRSKI-44 ; and define the shorter-resource versions of these well-known resources.
* the draft should 'inherit' the use of /.well-known/est/... resource as per draft-ietf-ace-coap-est , which already supports these for coap.

**Comment by mcr** [comment]
so, /.well-known/brski/rv   - request voucher
      /.well-known/brski/vs  - voucher status
      /.well-known/brski/es  - enrollment status

**Comment by mcr** [comment]
consensus on this, need to write text to go with it.
