### ISSUE TITLE
Update Section 5 Link Format example '/' character to '.'

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#54]
Section 5 has:

 </est/rv>; rt="ace.est/rv";ct=TBD2 TBD3
     </est/vs>; rt="ace.est/vs";ct=50 60
     </est/es>; rt="ace.est/es";ct=50 60
     </est/ra>; rt="ace.est/ra";ct=TBD2 TBD3

Because per RFC 6690 the regular rt attribute can only contain '-' and '.' and lowercase alphanumeric characters. The '.' is used to express hierarchy, so it would become:

 </est/rv>; rt="ace.est.rv";ct=TBD2 TBD3
     </est/vs>; rt="ace.est.vs";ct=50 60
     </est/es>; rt="ace.est.es";ct=50 60
     </est/ra>; rt="ace.est.ra";ct=TBD2 TBD3

**Comment by mcr** [comment]
Solved in #57
