### ISSUE TITLE
Implications/security of proximity-registrar-subject-public-key-info i.s.o. full certificate

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#55]
Some text is needed to consider the implications of using proximity-registrar-subject-public-key-info i.s.o. full certificate field proximity-registrar-cert. 
* For example if the Registrar is signing its Voucher Request with a different identity/keypair than the Registrar's server certificate. (Is such case allowed? If so, we need to enable the solution for this case. If not, we need to say so too.)
* The security considerations could indicate the 'loss' of security (is there any?) due to not using the full cert proximity-registrar-cert but only the public key of it.  If no loss of security it is also good to mention that.

See also email to ANIMA list for related topic on Registrar using different keypairs : https://mailarchive.ietf.org/arch/msg/anima/ot_rqS5d4gcBaK5yqmGd1I-vBvY/

**Comment by mcr** [comment]
In this constrained case of using proximity-registrar-subject-public-key-info, then the connection to the Registrar signing key would be lost if the Registrar signs with a different key.
The split can't be used some cases, so why have it?

      F
    /   \
  A    B

F - ancestor CA of A and B.
A - certificate used by southbound Registrar
B - certificate used by northbound Registrar in Voucher Request

Need a find a way to transport F, A and B (F and B are already sent) to MASA.

**Comment by mcr** [comment]
In the registrar voucher request, we need to add an attribute for "A", the southbound registrar.
(This can instead be included in the CMS signature as an additional certificate.)
If it is COSE, it can be x5u/etc.

1. BRSKI perspective should get an understanding of the consistency check **5.5.5**, when having two signatures.

2. For the constrained voucher, how do we carry this information if using a raw public key pin.

3. related to Request-Audit-Log, do we need COSE signed voucher requests, or is it better to just use CMS always, because then we have a consistent place to extra certificates.

**Comment by EskoDijk** [comment]
In general, for the signing-with-different-Registrar-identity to work in constrained-BRSKI we must also enabled it for regular-BRSKI. See issue https://github.com/anima-wg/anima-bootstrap/issues/146 where I just added a comment how I expect it to work; the additional southbound Registrar cert ('A') is sent together with F and B in the CMS signing structure. This proves to MASA that the Pledge is in proximity of the domain with CA 'F' which seems sufficient.  For COSE signing structure, cert 'A' can indeed be added to the x5bag.

1. See https://github.com/anima-wg/anima-bootstrap/issues/146 : the consistency check 5.5.5 needs updating to verify only proximity of the Pledge to any RA of the domain (CA), not strictly proximity to the RA operating the DTLS server that Pledge sees.

2. The constrained Voucher Req sent by Pledge may only carry the 'proximity-registrar-subject-public-key-info' : the MASA can directly compare this key-info to the full cert that is included in the CMS structure or in the COSE-X509 x5bag structure that Registrar is sending to MASA. And thus derive that Pledge is indeed in proximity of an RA of the domain (CA).

3. Don't fully understand the question here; since the southbound cert A is included in the Registrar's Voucher Req the MASA can (after verifying) use the full cert A to do any audit logging it needs to do, e.g. domainID calculation of 5.8.2 in BRSKI. If the Registrar uses COSE-x509 format it can add additional certs just like it can do in the CMS signing format.

**Comment by EskoDijk** [comment]
Given that 'wontfix' label is added; I assume we don't want to explain in details how a multi-identity Registrar setup works (that's for a future document to do).  I will assign to myself to check later on if there's a small paragraph of text we can add for the security considerations on this. Main consideration is quite simple: if the Registrar uses multiple identities it has to include all these identities in the x5bag or CMS in the RVR.  So MASA can then verify the proximity i.e. that all these different identities are belonging to one 'RA' entity of the same domain.
