### ISSUE TITLE
voucher status returns ACK

### ISSUE THREAD

**Issue by petervanderstok** [anima-wg/constrained-voucher#64]
When voucher status returns an 2.05 ACK, there are two possibilities
1) this is an ack annoucing later return of data
2) this is an ACK that anoounce that voucher is OK.

Currently they cannot be disctiguished

Suggestion, When voucher is OK return text in the payload like : "voucher OK"

**Comment by mcr** [comment]
@EskoDijk believes that this can be distinguished at the CoAP level, and will find the right text to distinguished.

**Comment by mcr** [comment]
How to distinguish between ACK without payload, and ACK with empty payload.

**Comment by EskoDijk** [comment]
In RFC7252 Section 5.2.2:
"When the server chooses to use a separate response, it sends the
   Acknowledgement to the Confirmable request as an Empty message."

So an Empty message of message-type ACK will acknowledge the request-message without providing a response yet.

Then in Section 3:
"Code 0.00 indicates an Empty message"

Also in Section 1.2 and 12.1:
"Empty Message       A message with a Code of 0.00; neither a request nor a response."
"0.00      Indicates an Empty message "

**Comment by EskoDijk** [comment]
One reason why a CoAP library might not allow the value "0.00" in the response, is when the library itself sends the Empty messages i.e. when that is not under control of the user's application code. So 0.00 is indeed not a proper response because it's a non-response :)  But I'm not familiar with libcoap so not sure if that applies there.

**Comment by csosto-pk** [comment]
Agreed @EskoDijk . We dealt with this in draft-ietf-ace-coap-est with Block and slow server responses. Excerpt from  
> In particular, a slow server can respond to an EST-coaps enrollment
>  request with an empty ACK with code 0.00, before sending the
>  certificate to the client after a short delay.

**Comment by petervanderstok** [comment]
HI Panos,

Forgot about that.
Will check a bit further in my code.
Anyway, I think similar text will be necessary in constrained voucher as
well.

cheerio,

Peter
Panos K. schreef op 2020-12-17 15:54:

> Agreed @EskoDijk [1] . We dealt with this in draft-ietf-ace-coap-est with Block and slow server responses. Excerpt from
> 
>> In particular, a slow server can respond to an EST-coaps enrollment
>> request with an empty ACK with code 0.00, before sending the
>> certificate to the client after a short delay.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/EskoDijk
[2]
https://github.com/anima-wg/constrained-voucher/issues/64#issuecomment-747486514
[3]

**Comment by petervanderstok** [comment]
Then in Section 3:
"Code 0.00 indicates an Empty message

missed that.

thanks,

peter
Esko Dijk schreef op 2020-12-17 14:04:

> In RFC7252 Section 5.2.2:
> "When the server chooses to use a separate response, it sends the
> Acknowledgement to the Confirmable request as an Empty message." 
> 
> So an Empty message of message-type ACK will acknowledge the request-message without providing a response yet. 
> 
> Then in Section 3:
> "Code 0.00 indicates an Empty message" 
> 
> Also in Section 1.2 and 12.1:
> "Empty Message A message with a Code of 0.00; neither a request nor a response."
> "0.00 Indicates an Empty message " 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/anima-wg/constrained-voucher/issues/64#issuecomment-747426491
[2]

**Comment by EskoDijk** [comment]
Keeping this issue open to add the required text to constrained-voucher!

**Comment by petervanderstok** [comment]
added text in desin consideration

**Comment by EskoDijk** [comment]
Updated the text proposal to make it more clear and use CoAP protocol terminology.
