### ISSUE TITLE
Fix consistency in usage of capitals in common terms like Pledge, Registrar, etc.

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#66]
Both forms are used in main text as well as in section headers: Pledge / pledge ; Registrar / registrar.
To decide what forms we want to use. BRSKI uses lowercase forms by default and uppercase form in section headers.

**Comment by csosto-pk** [comment]
I would go with capitalized Pledge and Registrar. It deviates from BRSKI a bit, but it makes the term distinction in the text clearer.

**Comment by mcr** [comment]
My preference, which I wish we had done in BRSKI (and maybe we can do in AUTH48) is that any term in the Terminology would be Capitalized.

**Comment by EskoDijk** [comment]
Fixed in commit https://github.com/anima-wg/constrained-voucher/commit/3f394c570776b8fe9f0d0abaf605c593dae4270d (name of commit mentions wrong issue number)
