### ISSUE TITLE
Add formal policy for MASA on what cert to pin

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#70]
Discussed in the design team call of 2021-01-14:
* proposed mandatory, or recommended, policy for MASA for what certificate to select for pinning in the Voucher
* MASA tries to reconstruct a chain and selects the highest-level CA certificate of the chain
* if no CA certificates included, the MASA pins the RA certificate of the Registrar
* Registrar can decide/direct what is being pinned by including more or less certs in the signing structure of its Voucher Request
* such policy isn't present in BRSKI at the moment, this would be updating BRSKI RFC.

**Comment by EskoDijk** [comment]
One question on the proposal: is this secure enough from the manufacturer's point of view?
What if the Registrar sends in a chain with a root CA cert that is a well-known PKIX root certificate like one from DigiCert or Comodo. The MASA would pin that certificate which would leave the Pledge trusting any one of the (millions?) of devices that have a certificate issued by this root.   On the other hand, such a "dangerous" wide-scope signed Voucher cannot be mis-used by Registrar (scenario e.g.: send it to another Registrar across the border) because due to freshness/nonce that Voucher is bound to the current DTLS session between Pledge and Registrar.  Outside that scope it wouldn't be valid anymore.

Assigning to @mcr to have a look at this question before writing the text.

**Comment by csosto-pk** [comment]
Yes, I think this is a valid concern. Pinning a CA cert means that the MASA / Registrar is controlling the PKI for the pledge. In usecases I have seen the trusted Registrar can be responsible from providing the EST-caops cacerts message, but that is not always the case. Sometimes pledges get the trusted certs from elsewhere or even using different protocols. 

I suggest the limit the scope of the pinning to the onboarding process. After onboarding, an EST-coaps /crt request or other means can be used by the pledge for the PKI it is part of and he should forget the pinned cert.

**Comment by EskoDijk** [comment]
@csosto-pk if the pinning is only for the scope of the current onboarding operation, then it shouldn't matter much what is pinned by MASA - any choice of cert (from the options that the Registrar provides) will work. 

For constrained pledges specifically, it might help to pin the "lowest" possible certificate in the hierarchy i.e. if the Registrar's RA certificate itself is pinned it saves the Pledge from doing chaining operations and storing many certificates in memory. Pinning the CA cert which signed the Registrar's RA cert (i.e. the "parent" of the Registrar's cert) is also a good option I think.

The Registrar ought to keep the certificates chain in the DTLS handshake, which is sent to Pledge, as small as possible: e.g. 1 or 2. This is more of a policy on the Registrar on what to include in its Voucher Request.

**Comment by csosto-pk** [comment]
Thx @EskoDijk . Makes sense. 

One more question which may have been discussed in the Thursday meeting which I am missing: 

> if no CA certificates included, the MASA pins the RA certificate of the Registrar

I think it needs to be spelled out if this cert is pulled from the DTLS connection or if the MASA caches the Registrar cert during setup. The latter has the disadvantage that it needs intervention if the cert changes. The former has the disadvantage of adding functionality to pull it from the connection which is missing from existing code. 

And one more question: What happens to the pinned cert after onboarding has taken place and we get a /crt request. I would expect the pinned cert gets overridden. No?

**Comment by EskoDijk** [comment]
@csosto-pk with this text "if no CA certificates ... Registrar" I meant that the Registrar has signed a Voucher Request (using either CMS signature or the new COSE X.509 signature) which only contains a single certificate, its own, in the signing structure. If the Registrar itself is not a CA but an RA then the MASA will only have a single RA certificate to choose from. So it can either refuse (if not allowed by its policies to trust a single RA cert) or else it has to pin this RA certificate.

Based on BRSKI design as today, the MASA shouldn't use any of the certs pulled from the TLS connection (not DTLS!) coming from the Registrar because these could use arbitrary authorization credentials like something vendor-provided, or a password, or a temporary certificate that was created through some sales API. I.e. unrelated to the domain of onboarding.  The signature contains the true domain of onboarding.

On the question what happens to the pinned cert: I believe the BRSKI design allows the Pledge to keep the pinned cert, see section 5.9.1 in BRSKI. Using the EST /crts is a SHOULD but not a MUST; the Pledge MAY use only the pinned cert as trust anchor.  However because this might cause the pinned cert to remain 'trusted' forever, and it can't be overwritten/replaced, it would make sense to have some means to overwrite/replace it - doing so after a /crts request seems easiest.

By the way there is one clear trigger telling the Pledge to do a /crts request: if the LDevID that it has just obtained doesn't chain to the pinned domain cert. That's a clear sign telling the Pledge it is missing some essential CA certificate(s) for the domain. If the new LDevID nicely chains to the pinned cert, there's no reason to issue the /crts request really.

**Comment by csosto-pk** [comment]
Understood. Thank you for the clarifications.
