### ISSUE TITLE
Add formal policy for Registrar on construction of signing cert/chain ?

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#71]
See also issue #70 that proposes a policy for the MASA on what to pin. Similarly a policy for the Registrar could be defined, such that the overall bootstrap process is as optimal as possible for constrained networks/devices.

Example: if the Registrar includes a stable Domain CA in the signature chain of its Voucher Request, and the MASA would pin this CA per the policy of #70, then the Pledge receiving this pinned domain CA can store it in its trust store per section 5.9.1 of BRSKI (and ignoring the SHOULD requirement there!) and skip the step of requesting EST /crts if the LDevID it obtains nicely chains to the pinned domain cert.  This saves an additional roundtrip and duplicate transmission of domain CA certificate.

Such an efficient solution can be reached if we include recommendations (SHOULD/RECOMMENDED level) in this draft for how the Registrar should sign, to support constrained device cases.

Maybe there are other policy elements also that we can include. One particular example for constrained devices is to limit the internal PKI hierarchy of the domain to at most 2 levels of CA; so we have either:
* LDevID -> Domain CA (root)
* LDevID -> Intermediate domain CA -> Domain CA (root)
adding more levels becomes a burden on the constrained device memory/processing, as well as on the constrained network.

**Comment by csosto-pk** [comment]
> * LDevID -> Domain CA (root)
> * LDevID -> Intermediate domain CA -> Domain CA (root)
>   adding more levels becomes a burden on the constrained device memory/processing, as well as on the constrained network.

Agreed, but not sure if the draft can dictate the chain length.

**Comment by EskoDijk** [comment]
Text proposed; the chain length story was left out of this.
