### ISSUE TITLE
in the pinned-raw-public-key scenario, how does certificates and renew work?

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#77]
If a Registrar (P3) is pinned by public key, 

1. then what happens to the /crts call?
2. does the pledge do an enrollment?
3. how does renewal work?

If the goal of the pinned-public-key is to eliminate PKIX operational code from the pledge, then how would the pledge enroll anyway? What does such a pledge do with a certificate?

Or, are we just eliminating *PKIX* certificates, but opening things to COSE/CWT/CBOR certificates?

Is /crts call replaced with a list of public keys?  Using a CBOR array return?
Or enumeration like in #72?

**Comment by EskoDijk** [comment]
I think the chosen enrollment method (EST, or else a variant of EST using RPKs, or CMP, or .... ) should not depend on how the pinned entity is identified: by pinned cert, or by pinned RPK.
See also #78 comments (goal 4.) for an example of how public-key pinning could be used -- if we want to allow that -- just as a quick, secure way to reduce Voucher size without necessarily implying that some new form of RPK-enrollment is required.

In most cases where the Pledge supports 1 enrollment method it will just attempt that one; and either succeed or fail.
In cases where the Pledge supports 2 or more methods it will attempt these one by one - trial and error, or it may do this smarter if we define a future standard mechanism in #73 to let the Registrar signal preferred enrollment methods. But that's outside the current document scope.

For the current spec this brings back the question to this case:
what if the Pledge supports (as one of its method, or as the *only* method - doesn't matter)  a method of enrollment where not a certificate is obtained but rather an identity by RPK pair is enrolled into the domain?
Unfortunately EST cannot do this so we have to write that this is outside the scope of this document.  The current draft is rather tied to EST as you can find by searching "EST-" and "-EST" strings in the draft.

So here we really don't have to go into details on out-of-scope things. We can say that the "RPK pinning" is useful for some new certificate-less enrollment method without giving details on what this method should be.

**Comment by mcr** [comment]
I agree that in general, the enrollment method should not dictate how things are pinned.
But, if the goal of using RPK pinning is to avoid PKIX operations, with the intention of not doing certificate enrollment (6tisch, WPA-PSK wifi case), then there is clearly some interaction at the policy level.
Do you agree with that?

**Comment by EskoDijk** [comment]
@mcr Agree.  In principle the MASA (vendor) decides what is pinned, based on knowing what the Pledge can support. When a Pledge supports multiple pinning methods the MASA can take this decision based on various things like e.g. impact on Voucher size, security level, reusability of Voucher (e.g. relevant for nonceless Vouchers) , or even known customer preferences for the Voucher and/or enrollment method.

I think the signaling of enrollment method to a Pledge that supports >= 2 methods could be any of these:
1. Not signaled - Pledge itself uses discovery or trial/error to find the right method
2. MASA signals in a custom field, or via an existing field, of the Voucher - e.g. it could have a Pledge that treats a pinned RPK as a signal to use "cert-less enroll" even though this way of signaling is not IETF-standardized.
3. Included as data field in an out-of-band message sent to the Pledge with a "Join now" command.
4. MASA signals in a standardized field in the Voucher - this would be a new field updating RFC 8366; that comes with an IANA registry for enrollment methods.

In case the customer has a preference to use a specific enrollment method, there are various ways to express this preference:
1. Implicit to Pledge - by offering only 1 method to the Pledge (who can e.g. discover or try multiple methods by trial &error)
2. Explicit to MASA, not standardized - e.g. via custom exchange between Registrar/MASA or via sales integration systems.  Once the MASA knows the preference it can signal the Pledge via one of above methods 2/3/4.
3. Explicit to MASA, standardized by IETF - as 2. but then an IETF-standardized method to include preference in the Registrar Voucher Request.

But I don't think we have to go into detail on all of this in the present draft.  We can just make clear that the MASA decides the pinning method and that the pinning method is not **necessarily** tied to the enrollment method, but in many practical cases it is.

**Comment by EskoDijk** [comment]
Current text of commit https://github.com/anima-wg/constrained-voucher/commit/b46d91292295afbac3b69442d009cf5b34780108 addresses this issue also; to be reviewed by co-authors.

The general idea is that MASA decides whether to pin RPK based on knowledge of what the Pledge supports and the policy of what it wants to pin in this particular case.
For example, if Pledge only supports RPK pinning and no EST/certificates then it pins RPK and the Pledge will after verification attempt to do its non-EST enrollment method. It has no code for EST enrollment; so it will not do an EST /crts call. It will do maybe a similar call defined by the cert-less equivalent of EST but that's outside our draft's current scope.

**Comment by mcr** [comment]
also related #77

**Comment by EskoDijk** [comment]
Proposing to close the current issue, text has been provided already by related commits to address this:
* RPK pinning can be used independently; has no impliciations on the following enrollment process in principle.
* Pledge decides whether to use RPK or cert for proximity-registrar
* Pledge decides whether to use RFC 7250 server-RPK-extension in handshake
* MASA decides whether to pin RPK or cert in Voucher
* Renewal works as normal for EST, if Pledge did EST enrollment
* If Pledge does not do EST enrollment, it just performs another method
* If Pledge is so minimal that it can't do PKIX operations it cannot do re-enroll and it cannot establish trust to any RA of the domain other that its initial Registrar/RA. Redo bootstrap (factory reset) is always an option then.

If any loose ends we may find out during a next full review of the draft! (And open a new issue specific to that.)
