### ISSUE TITLE
subordinate CA vs intermediate CA

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#85]
As explained in: https://mailarchive.ietf.org/arch/msg/anima/3tNwWb9gBacdYMTr1TtXzSa_3_Q/

it is unclear when one should say "subordinate" vs "intermediate".

**Comment by EskoDijk** [comment]
EST (RFC 7030) calls it "subordinate CA" so my proposal is to stick to this terminology, since we base ourselves on EST for this draft. We could add a terminology section definition of what we mean with subordinate CA although in RFC 7030 it is clear from the context already.

**Comment by csosto-pk** [comment]
+1 on subordinate. Not a fan of adding a terminology section. RFC7030 did not define it either. Let's keep it simple.

**Comment by mcr** [comment]
Okay, going with subordinate.
Look at the federal bridge CA stuff at: https://fpki.idmanagement.gov/tools/fpkigraph/ and see how many are marked "intermediate", and now I know it's not the term for us :-)
