### ISSUE TITLE
verify ability to validate certificate chains, and document in an appendix/example

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#88]
In section ## MASA Pinning Policy, point 2, we assert that it is possible to validate a chain.  Validate that this can be done with OpenSSL, mbedTLS, WolfSSL, and include some reference code in an appendix.

**Comment by EskoDijk** [comment]
For mbedTLS see: https://tls.mbed.org/api/group__x509__module.html#ga98ed4504e4f832b735a230acf54fcde3

Partial example, for single cert 'cert':   (chain in 'cert' is also possible according to documentation)

```
mbedtls_x509_crt cert;
mbedtls_x509_crt caCert;
uint32_t         certVerifyResultFlags;
...
int result = mbedtls_x509_crt_verify(&cert, &caCert, NULL, NULL, &certVerifyResultFlags, NULL, NULL);
```

**Comment by mcr** [comment]
@mcr will document this for wolfSSL.

**Comment by mcr** [comment]
@petervanderstok to embellish mbedTLS.

**Comment by csosto-pk** [comment]
Code snippet for OpenSSL stolen from https://github.com/openssl/openssl/blob/3c2bdd7df95b5ce2aa238de9e39e0e70125bd7e6/apps/verify.c 

`
    X509 *x = NULL;
    int i = 0, ret = 0;
    X509_STORE_CTX *csc;
    STACK_OF(X509) *chain = NULL;
    int num_untrusted;

    x = load_cert(file, "certificate file");
    if (x == NULL)
        goto end;

    csc = X509_STORE_CTX_new();
    if (csc == NULL) {
        BIO_printf(bio_err, "error %s: X.509 store context allocation failed\n",
                   (file == NULL) ? "stdin" : file);
        goto end;
    }

    X509_STORE_set_flags(ctx, vflags);
    if (!X509_STORE_CTX_init(csc, ctx, x, uchain)) {
        X509_STORE_CTX_free(csc);
        BIO_printf(bio_err,
                   "error %s: X.509 store context initialization failed\n",
                   (file == NULL) ? "stdin" : file);
        goto end;
    }
    if (tchain != NULL)
        X509_STORE_CTX_set0_trusted_stack(csc, tchain);
    if (crls != NULL)
        X509_STORE_CTX_set0_crls(csc, crls);

    i = X509_verify_cert(csc);
    if (i > 0 && X509_STORE_CTX_get_error(csc) == X509_V_OK) {
        BIO_printf(bio_out, "%s: OK\n", (file == NULL) ? "stdin" : file);
        ret = 1;
        if (show_chain) {
            int j;

            chain = X509_STORE_CTX_get1_chain(csc);
            num_untrusted = X509_STORE_CTX_get_num_untrusted(csc);
            BIO_printf(bio_out, "Chain:\n");
            for (j = 0; j < sk_X509_num(chain); j++) {
                X509 *cert = sk_X509_value(chain, j);
                BIO_printf(bio_out, "depth=%d: ", j);
                X509_NAME_print_ex_fp(stdout,
                                      X509_get_subject_name(cert),
                                      0, get_nameopt());
                if (j < num_untrusted)
                    BIO_printf(bio_out, " (untrusted)");
                BIO_printf(bio_out, "\n");
            }
            sk_X509_pop_free(chain, X509_free);
        }
    } else {
        BIO_printf(bio_err,
                   "error %s: verification failed\n",
                   (file == NULL) ? "stdin" : file);
    }
    X509_STORE_CTX_free(csc);

 end:
    if (i <= 0)
        ERR_print_errors(bio_err);
    X509_free(x);

    return ret;`

**Comment by mcr** [comment]
> 

mcr won't document this.
