### ISSUE TITLE
are proximity-registrar-xxx names too long

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#95]
While the verbosity of the names
  proximity-registrar-subject-public-key-info
  proximity-registrar-sha256-of-subject-public-key-info

is not a problem for on-the-wire communications, as they are mapped to a single SID.
They are becoming a problem for the document itself as they do not fit on the page.

Should we attempt to adopt shorter names?

**Comment by petervanderstok** [comment]
Yes, we should.

They are also difficult to remember and difficult to use in a
discussion.

Peter
Michael Richardson schreef op 2021-02-25 02:14:

> While the verbosity of the names
> proximity-registrar-subject-public-key-info
> proximity-registrar-sha256-of-subject-public-key-info 
> 
> is not a problem for on-the-wire communications, as they are mapped to a single SID.
> They are becoming a problem for the document itself as they do not fit on the page. 
> 
> Should we attempt to adopt shorter names? 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/anima-wg/constrained-voucher/issues/95
[2]

**Comment by EskoDijk** [comment]
Here some suggestions:

proximity-registrar-public-key
proximity-registrar-public-key-hash   (or: proximity-registrar-public-key-sha256)

proximity-registrar-spki
proximity-registrar-spki-hash       (or: proximity-registrar-spki-sha256)

proximity-registrar-subj-public-key
proximity-registrar-subj-public-key-hash

proximity-registrar-subject-pk
proximity-registrar-subject-pk-hash

**Comment by mcr** [comment]
proximity-registrar-pubk
proximity-registrar-pubk-sha256

**Comment by mcr** [comment]
or pubk, or pk.
