### ISSUE TITLE
Update all enroll/voucher status examples to use 'brski' paths and use correct payload format

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#97]
BRSKI-45 recently clarified and updated the payload formats; this needs to be reflected also in our examples.
Also, the paths need updating to /brski paths (not /est namespace).

**Comment by mcr** [comment]
I've been grep'ing and searching, but I haven't found any well-known/est left.

**Comment by EskoDijk** [comment]
@mcr I've assigned this issue to me, to fix the last few remaining occurrences. (There are)
But before I can proceed with this we really need to merge in the pending PR https://github.com/anima-wg/constrained-voucher/pull/94 !

**Comment by EskoDijk** [comment]
The indicated issue wasn't completely fixed on Apr 15 for some reason. Now, this new PR fixes it: https://github.com/anima-wg/constrained-voucher/pull/119
