### ISSUE TITLE
when using pinned RPK followed by EAP-TLS in WPA-Enterprise, can we get a RPK for the server?

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#98]
XXX - if we the next step is to do EAP-TLS for WPA-Enteprise use, can we get a Raw Public Key for the server somewhere?

**Comment by EskoDijk** [comment]
This looks out of scope for the draft, since we cover DTLS used for BRSKI and for EST. 
Or would a Pledge first use BRSKI-over-DTLS and then EAP-TLS?  Or is there an EAP-DTLS maybe?

Nevertheless an interesting question, as I understand it the server must signal to the Pledge the RPK so that the Pledge can compare this RPK to the one pinned in its Voucher. What about using the public key of the EAP-TLS server's certificate?  Or, then why not pin the entire EAP-TLS server's certificate?

**Comment by csosto-pk** [comment]
> Or would a Pledge first use BRSKI-over-DTLS and then EAP-TLS? Or is there an EAP-DTLS maybe?

As far as I know in Wi-Sun and 802.15.4 it is EAPoLAN and EAOoUDP in the Mesh Network. It is EAP-TLS from the first aggregation point (Mesh Routers) to the Radius server.

**Comment by EskoDijk** [comment]
In case we want to cover starting with "constrained BRSKI" followed by something "non-EST", then we should be explicit about it and it also needs a name. Currently we name the protocol "BRSKI-EST" which forces EST to be part of the solution. In other words when you're not using EST you can't have "BRSKI-EST" in my view.  Additionally, the current draft is very much presented as "an extension of ace-coap-est" so given that it's impossible to just remove the EST aspect from it!

We should discuss the scope in a design team meeting, before going into detail on the question of this issue.

**Comment by csosto-pk** [comment]
> We should discuss the scope in a design team meeting, before going into detail on the question of this issue.

Personally I am fine with that. We started with EST, then BRSKI, then brought EST in the COAP world and then BRSKI to the COAP world. Adding complexity for different enrollments after the bootstrapping would increase the scope significantly imo. If someone wanted to enroll with anything else than EST then a new draft would be the way to go.

**Comment by mcr** [comment]
The base scenario that I'm considering is that we do some form of constrained BRSKI.    Let's forget about what kind for the moment.
*EST is used to enroll an LDevID.  The pledge then turns around and does "WPA-Enterprise" (i.e. EAP-TLS with certificate authentication).
Given that the voucher provided an RPK, and the LDevID that was issued is can be validated with that RPK as a trust-anchor, is this enough to also validate the AAA-server's certificate?

(Cisco people may hate me, but to me, CoAP/DTLS over EAP looks way better than the EAP-TLS methods which have to simulate TCP (poorly), particularly EAP-TEAP.  Since WPA-Enterprise is not EAP-TEAP, I see no reason why we EAP-TEAP is a good thing to use)

**Comment by EskoDijk** [comment]
@mcr  So the base scenario is first BRSKI (/rv voucher request), then EST to enroll with LDevID (e.g. /sen) , the following by something else, "WPA-Enterprise".  That sounds within scope of our draft still, it is BRSKI-EST. So for me ok if we outline a possible next step to this, if it has distinct advantages and is  not too extensive.

**Comment by petervanderstok** [comment]
@all

I am not sure what this will mean for the text and the subject scope of 
the draft. Sorry,

Peter

> @mcr [1] So the base scenario is first BRSKI (/rv voucher request), 
> then EST to enroll with LDevID (e.g. /sen) , the following by something 
> else, "WPA-Enterprise". That sounds within scope of our draft still, it 
> is BRSKI-EST. So for me ok if we outline a possible next step to this, 
> if it has distinct advantages and is not too extensive.
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].


Links:
------
[1] https://github.com/mcr
[2] 
https://github.com/anima-wg/constrained-voucher/issues/98#issuecomment-829006014
[3]

**Comment by EskoDijk** [comment]
@petervanderstok  What I mean is that the BRSKI-EST part of the protocol is exactly the scope of our draft. I don't want to venture much beyond that, but if we have some words to say about "glueing" another protocol to BRSKI-EST which makes use of the security material of BRSKI-EST (like Voucher, pinned RPK, pinned cert, LDevID, or any combination thereof) then I'm ok if we say it. (In a few sentences or a few paragraphs at most. Or in an appendix)

**Comment by mcr** [comment]
> @petervanderstok What I mean is that the BRSKI-EST part of the protocol is exactly the scope of our draft. I don't want to venture much beyond that, but if we have some words to say about "glueing" another protocol to BRSKI-EST which makes use of the security material of BRSKI-EST (like Voucher, pinned RPK, pinned cert, LDevID, or any combination thereof) then I'm ok if we say it. (In a few sentences or a few paragraphs at most. Or in an appendix)

So either an appendix, or another document.
